---
- name: ansible playbook to copy a file
  hosts: nodes
  become: true
  tasks:
  - name: copy a file
    copy:
      src: /opt/sai-playbooks/files/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: john
