---
- name: this playbook install packages
  hosts: nodes
  become: true
  tasks:
  - name: install package
    yum:
     name: "{{ item }}"
     state: installed
    with_items:
      - git
      - make
      - gcc
      - wget
      - telnet
      - gzip
